config/routes.rb
Rails.application.routes.draw do
  root to: 'bicycles#index'
  get 'bicycles/search_location' => 'bicycles#search_location'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  def index
  end

  def search_location
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/views/bicycles/index.html.erb
<body>
  <main>
    <div class="main-wrap">
      <header>
        <div class="header-wrap">
          <div class="site_title_header">
            <%= link_to image_tag('header-logo.png', class:'header-logo'), "/" %>
          </div>
        </div>
      </header>
      <div class="main-content">
        <div class="main-image">
          <%= image_tag 'logo.png', class:'main-logo' %>
        </div>
        <div class="main-text">
          <p>このサイトでは位置情報を利用しています。</p><br>
          <p>必ず位置情報をオンにして利用してください。</p>
        </div>
        <div class="main-btn">
          <%= link_to bicycles_search_location_path, class:'btn btn-main btn-c' do%>
          <i class="fas fa-bicycle"></i>　現在地から探す
          <i class="fas fa-search-location"></i>
          <%end%>
        </div>
      </div>
      <footer>
        <div class="footer-wrap">
          <div class="footer-info">
            <small class="footer-text"> &copy; 2020 ATSUSHI All rights Reserved.</small>
          </div>
        </div>
      </footer>
    </div>
  </main>
</body>

app/views/bicycles/search_location.html.erb
<body>
  <main>
    <div class="main-wrap">
      <header>
        <div class="header-wrap">
          <div class="site_title_header">
            <%= link_to image_tag('header-logo.png', class:'header-logo'), "/" %>
          </div>
        </div>
      </header>
        <div id="gmap"></div> <!-- 地図を表示する領域 -->
      <footer>
        <div class="footer-wrap">
          <div class="footer-info">
            <small class="footer-text"> &copy; 2020 ATSUSHI All rights Reserved.</small>
          </div>
        </div>
      </footer>
    </div>
  </main>
</body>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCd0HjEkvdORg2mGfvCU4RX1xapeDLEUBQ&callback=initMap&libraries=places">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>チャリトメ</title>
    <meta http-equiv="content-type" charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <meta property='og:type' content='webapp'>
    <meta property='og:title' content='チャリトメ'>
    <meta property='og:url' content='https://charitome.com/'>
    <meta property='og:description' content='チャリトメ'>
    <meta name="description" content="周辺の駐輪場を検索するアプリです。" />
    <link rel="stylesheet" href="https://unpkg.com/sanitize.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>